server:
  port: @eureka.server02.server.port@
spring:
  application:
    name: eureka-server-02
  #Disabling Ribbon with Eureka Server and Client starters
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  security:
    user:
      name: @eureka.server02.security.username@
      password: @eureka.server02.security.password@
eurekaServer:
  name: @eureka.server01.instance.hostname@
  port: @eureka.server01.server.port@
  usernme: @eureka.server01.security.username@
  password: @eureka.server01.security.password@
eureka:
  instance:
    hostname: @eureka.server02.instance.hostname@
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eurekaServer.usernme}:${eurekaServer.password}@${eurekaServer.name}:${eurekaServer.port}/eureka